WebApplication1/Models/EMPLEADO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.EMPLEADO1 = new HashSet<EMPLEADO>();
            this.META_VENTA = new HashSet<META_VENTA>();
            this.ORDEN_DE_COMPRA = new HashSet<ORDEN_DE_COMPRA>();
        }
    
        public int nit { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string direccion { get; set; }
        public int telefono { get; set; }
        public int celular { get; set; }
        public string email { get; set; }
        public int idTipoEmpleado { get; set; }
        public Nullable<int> idJefe { get; set; }
        public int idUsuario { get; set; }
        public string idVehiculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO> EMPLEADO1 { get; set; }
        public virtual EMPLEADO EMPLEADO2 { get; set; }
        public virtual TIPO_EMPLEADO TIPO_EMPLEADO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<META_VENTA> META_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_DE_COMPRA> ORDEN_DE_COMPRA { get; set; }
    }
}

WebApplication1/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class EmpleadoController : Controller
    {
        private DataBase datos = new DataBase();
        
        
        public async Task<ActionResult> Index(int? nit)
        {
            EMPLEADO empleado = await datos.EMPLEADO.FindAsync(nit);
            ViewBag.nombreJefe = nombreJefe(empleado);
            ViewBag.apellidoJefe = apellidoJefe(empleado);
            return View(empleado);
        }
        
        
        public string nombreJefe(EMPLEADO empleado) {
            
                EMPLEADO jefe = datos.EMPLEADO.FirstOrDefault(e => e.nit == empleado.idJefe);
                return jefe.nombre;  
        }

        
        public string apellidoJefe(EMPLEADO empleado)
        {
                EMPLEADO jefe = datos.EMPLEADO.FirstOrDefault(e => e.nit == empleado.idJefe);
                return jefe.apellido;
        }
        public async Task<ActionResult> Main2(int? nit)
        {
            EMPLEADO empleado = await datos.EMPLEADO.FindAsync(nit);
            return View(empleado);
        }

        
        public async Task<ActionResult> GenerarOrden(int? nit)
        {
            EMPLEADO empleado = await datos.EMPLEADO.FindAsync(nit);
            return View(empleado);
        }

    }
}

WebApplication1/Views/Empleado/GenerarOrden.cshtml
@model WebApplication1.Models.ORDEN_DE_COMPRA

@{
    ViewBag.Title = "GenerarOrden";
}

<div class="text-center align-content-center">
    <h1>Nueva Orden de Compra</h1>
</div>
<hr />


<div class="row text-center justify-content-xl-center align-content-center">
    <div class="col-md-4">
        <form action="/Home/Loguearse" method="post">
            <div class="form-group">
                <label class="control-label">Usuario</label>
                <input type="text" class="form-control" name="usuarioS" value="" />
            </div>
            <div class="form-group">
                <label class="control-label">Ingresa tu contraseña</label>
                <input type="password" class="form-control" name="password" value="" />
            </div>
            <div class="form-group">
                <button class="btn btn-primary">Iniciar Sesion</button>
            </div>
        </form>
    </div>
</div>

WebApplication1/Views/Empleado/Index.cshtml
@model WebApplication1.Models.EMPLEADO

@{
    ViewBag.Title = "GenerarOrden";
}
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DIPROMA", "Main2", "Empleado", new { nit = Model.nit }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Información Personal", "Index", "Empleado", new { nit = Model.nit }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Generar Ordenes De Compra", "GenerarOrden", "Empleado", new { nit = Model.nit }, new { @class = "navbar-brand" })</li>
                    <li><a href="/Empleado/Factura">Generar Facturas</a></li>
                    <li><a href="/Home/Logout">Cerrar Sesion</a></li>
                </ul>
            </div>
        </div>
    </div>

<h1>INFORMACIÓN EMPLEADO-VENDEDOR</h1>
<table class="table">
    <tr>
        <th>
            Nombre Empleado Vendedor
        </th>
        <th>
            Apellido Empleado Vendedor
        </th>
        <th>
            Fecha Nacimiento
        </th>
        <th>
            Dirección
        </th>
        <th>
            Telefono
        </th>
        <th>
            Celular
        </th>
        <th>
            Email
        </th>
        <th>
            Jefe
        </th>
        <th>
            Usuario
        </th>
        <th></th>
    </tr>


    <tr>
        <td>
            @Model.nombre
        </td>
        <td>
            @Model.apellido
        </td>
        <td>
            @Model.fechaNacimiento
        </td>
        <td>
            @Model.direccion
        </td>
        <td>
            @Model.telefono
        </td>
        <td>
            @Model.celular
        </td>
        <td>
            @Model.email
        </td>
        <td>
            @ViewBag.nombreJefe   @ViewBag.apellidoJefe
        </td>
        <td>
            @Model.idUsuario
        </td>
    </tr>

</table>

WebApplication1/Views/Empleado/Main2.cshtml
@model WebApplication1.Models.EMPLEADO
@{
    ViewBag.Title = "View";
}

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DIPROMA", "Main2", "Empleado", new { nit = Model.nit }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Información Personal", "Index", "Empleado", new { nit = Model.nit }, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Generar Ordenes De Compra", "GenerarOrden", "Empleado", new { nit = Model.nit }, new { @class = "navbar-brand" })</li>
                    <li><a href="/Empleado/Factura">Generar Facturas</a></li>
                    <li><a href="/Home/Logout">Cerrar Sesion</a></li>
                </ul>
            </div>
        </div>
    </div>

<div class="text-center align-content-center">
    <h1 class="display-4">BIENVENIDO</h1>
    <p>Sistema de Ventas  DIPROMA</p>
</div>
<div class="text-center align-content-center">
    <img src="~/img/portada.png" alt="ASP.NET" class="img-responsive " />
</div>